os: linux
dist: xenial
services:
  - docker

language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'

install: 'pip install -e .[test]'

script:
  - flake8
  - pytest --cov

after_success:
  - codecov

jobs:
  include:
    - stage: Mypy type check
      python: '3.8'
      script: mypy pyinfra/ pyinfra_cli/

    - stage: Local integration test
      python: '3.8'
      script: pytest -m local

    - stage: Docker integration test
      python: '3.8'
      script: travis_wait pytest -m docker
      if: branch = master
